### ISSUE TITLE
FE Preview switch failed

### ISSUE THREAD

**Issue by Zeromax** [Zeromax/contao-sb-admin#32]
```
[10-Jan-2016 10:16:10 Europe/Zurich] PHP Fatal error: Uncaught exception 'Exception' with message 'File system/themes/sb-admin/basic.css does not exist' thrown in /home/meinwebspace/public_html/horeb/system/modules/core/library/Contao/Combiner.php on line 134
#0 /home/meinwebspace/public_html/contao/system/modules/core/templates/backend/be_switch.html5(14): Contao\Combiner->add('system/themes/s...')
#1 /home/meinwebspace/public_html/contao/system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/meinwebspace/...')
#2 /home/meinwebspace/public_html/contao/system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 /home/meinwebspace/public_html/contao/system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 /home/meinwebspace/public_html/contao/system/modules/core/classes/BackendTemplate.php(107): Contao\BackendTemplate->parse()
#5 /home/meinwebspace/public_html/contao/system/modules/core/controllers/BackendSwitch.php(146): Contao\BackendTemplate->output()
#6 /home/meinwebspace/public_html/contao/contao/switch.php(20): Contao\BackendSwitch->run()
#7 {main}
```

See https://community.contao.org/de/showthread.php?59192-sb-admin-Alternatives-Backend-Theme/page3&p=395511&viewfull=1#post395511

**Comment by Zeromax** [comment]
fixed in 921fb8c
